export const FETCH_SPACES_LIST_REQUEST = "FETCH_SPACES_LIST_REQUEST";
export const FETCH_SPACES_LIST_SUCCESS = "FETCH_SPACES_LIST_SUCCESS";
export const FETCH_SPACES_LIST_FAILURE = "FETCH_SPACES_LIST_FAILURE";
